### ISSUE TITLE
Home Page: Events - Card Design/Implementation

### ISSUE THREAD

**Issue by BluuArc** [lugatuic/lug.cs.uic.edu-2018#10]
Design and implement how event cards should look. To be done once structure of events are decided #7 

Be sure to look at the slack channel for the initial whiteboard design.

**Comment by jakeraffe** [comment]
The left and right arrows on the events carousel stay white when light theme is switched on witch hides them.

**Comment by BluuArc** [comment]
Yup, I've already noted it in PR #35

**Comment by jakeraffe** [comment]
Whoops sorry. I didnt see that.

**Comment by BluuArc** [comment]
Initial implementation finished in #35
