### ISSUE TITLE
Backend: File Structure of API Logic

### ISSUE THREAD

**Issue by BluuArc** [lugatuic/lug.cs.uic.edu-2018#39]
Following the discussion of splitting out the Officer code in PR #31, document how modules/endpoints are to be added to the server (code, file structure, etc.).

**Comment by BluuArc** [comment]
Based on discussions, we're going to use [this](https://github.com/gothinkster/flask-realworld-example-app) as a base.

**Comment by wilt00** [comment]
WIP in branch https://github.com/lugatuic/lug.cs.uic.edu-2018/tree/refactor-flask

**Comment by BluuArc** [comment]
Done via #62
