### ISSUE TITLE
Office Policy page

### ISSUE THREAD

**Issue by Benbigmac** [lugatuic/lug.cs.uic.edu-2018#53]
This will be a button on the about page with a list of the LUG office policies, which while similair to the ACM's have several differences:
General Policies

Pick up after yourself
Do not leave personal items in the office (LUGis not responsible for the loss or theft of valuables)
Try not to disturb others (excessive noise, etc.)
Keep your hands to yourself (see Assault Policy below)
Door Policy

The Lug Office is open anytime there is a valid keyholder present. In all other instances the doors should remain closed and locked, and the last keyholder to leave is responsible for ensuring that this is the case.

Assault Policy

Assault is defined as any offensive and intentional physical contact with another person without their consent.

Violator is permanently banned from LUG and a police report will be filed.
A pardon may be granted by majority vote of the executive council\

Space Policy
The LUG office is a shared resource and thus, we have many people coming in any time during the day. While you are free to use the desks and chairs of the ACM, you may not 'hog' a seat. You must give up your seat to another person that wants to do any of the following:
Study
Work
SIG related educational activities
Educating oneself (reading articles, newspapers, etc) NOT comics, reddit, digg, etc
Developing
The ACM has no assigned seats and therefore, you must pick up after yourself when you leave. If you are to leave momentarily, please leave a note so nobody takes your seat. 

Freezer Policy
individuals seeking to use the freezer must seek permission from a LUG officer or councilmember.
Organizations that seek to use the freezer to store items must seek permission from a LUG officer at least 1 week prior.
Violations of this will result in items stored being thrown out and with no compensation for any items.

Violations to the Policy

First time offenders: You will not be allowed to use the office or the office resources for a period of 24 hours
Second time offenders: You will not be allowed to use the office or the office resources for a period of one week
Repeat offenders: At the discretion of the officers, your office privileges will be suspended for any period of time including indefinitely.
Fair warning and reason will be given prior to the ban

**Comment by BluuArc** [comment]
Finished with #55
